// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRh4dVZ3OWdppp8dXRtXBby8UnVCaFwY',
    appId: '1:525042968097:web:b51a4f309cafa7b81c2560',
    messagingSenderId: '525042968097',
    projectId: 'smart-iris',
    authDomain: 'smart-iris.firebaseapp.com',
    databaseURL: 'https://smart-iris-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iris.firebasestorage.app',
    measurementId: 'G-911Z3C35QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdD_a1ITsvwrKov8z7PeBvrny0EBChBfk',
    appId: '1:525042968097:android:f2a5517ce2b8f18e1c2560',
    messagingSenderId: '525042968097',
    projectId: 'smart-iris',
    databaseURL: 'https://smart-iris-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iris.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0UlJA7Pi6VnEyQC1x6UWvuH2vie3KrI',
    appId: '1:525042968097:ios:c79ef1043be558011c2560',
    messagingSenderId: '525042968097',
    projectId: 'smart-iris',
    databaseURL: 'https://smart-iris-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iris.firebasestorage.app',
    iosBundleId: 'com.example.irisNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0UlJA7Pi6VnEyQC1x6UWvuH2vie3KrI',
    appId: '1:525042968097:ios:c79ef1043be558011c2560',
    messagingSenderId: '525042968097',
    projectId: 'smart-iris',
    databaseURL: 'https://smart-iris-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iris.firebasestorage.app',
    iosBundleId: 'com.example.irisNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZRh4dVZ3OWdppp8dXRtXBby8UnVCaFwY',
    appId: '1:525042968097:web:8fcf045d69e7d2791c2560',
    messagingSenderId: '525042968097',
    projectId: 'smart-iris',
    authDomain: 'smart-iris.firebaseapp.com',
    databaseURL: 'https://smart-iris-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iris.firebasestorage.app',
    measurementId: 'G-1PG2PL4DBY',
  );

}